name: Conditional Jobs Workflow
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Build Steps
        run: |
          echo "Build Job Getting Executed"
          ls building.txt
  testing: 
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
      - name: Testing Steps
@@ -18,6 +19,7 @@ jobs:
          sleep 10
  deployment: 
    runs-on: ubuntu-latest
    if: always()
    needs: [build, testing]
    steps:
      - name: Deployment Steps
